### ISSUE TITLE
Toast related error encountered 

### ISSUE THREAD

**Issue by kiloutyg** [kiloutyg/docauposte2#298]
toast.js:15  Uncaught ReferenceError: bootstrap is not defined
    at HTMLDocument.showToast (toast.js:15:17)
    at dispatch (turbo.es2017-esm.js:344:1)
    at Session.notifyApplicationAfterPageLoad (turbo.es2017-esm.js:3158:1)
    at Session.visitCompleted (turbo.es2017-esm.js:3062:1)
    at Navigator.visitCompleted (turbo.es2017-esm.js:2417:1)
    at Visit.complete (turbo.es2017-esm.js:1787:1)
    at turbo.es2017-esm.js:1854:1
    at async Visit.render (turbo.es2017-esm.js:2037:1)
showToast @ toast.js:15
dispatch @ turbo.es2017-esm.js:344
notifyApplicationAfterPageLoad @ turbo.es2017-esm.js:3158
visitCompleted @ turbo.es2017-esm.js:3062
visitCompleted @ turbo.es2017-esm.js:2417
complete @ turbo.es2017-esm.js:1787
(anonymes) @ turbo.es2017-esm.js:1854
await in (anonymes) (asynchrone)
render @ turbo.es2017-esm.js:2037
await in render (asynchrone)
loadResponse @ turbo.es2017-esm.js:1845
visitRequestCompleted @ turbo.es2017-esm.js:2078
recordResponse @ turbo.es2017-esm.js:1831
simulateRequest @ turbo.es2017-esm.js:1818
issueRequest @ turbo.es2017-esm.js:1808
visitStarted @ turbo.es2017-esm.js:2065
start @ turbo.es2017-esm.js:1767
startVisit @ turbo.es2017-esm.js:2341
visitProposedToLocation @ turbo.es2017-esm.js:2060
visitProposedToLocation @ turbo.es2017-esm.js:3049
proposeVisit @ turbo.es2017-esm.js:2331
formSubmissionSucceededWithResponse @ turbo.es2017-esm.js:2387
await in formSubmissionSucceededWithResponse (asynchrone)
requestSucceededWithResponse @ turbo.es2017-esm.js:790
receive @ turbo.es2017-esm.js:546
perform @ turbo.es2017-esm.js:521
await in perform (asynchrone)
start @ turbo.es2017-esm.js:743
submitForm @ turbo.es2017-esm.js:2346
formSubmitted @ turbo.es2017-esm.js:3076
FormSubmitObserver.submitBubbled @ turbo.es2017-esm.js:951
Afficher 26 plus de cadres
Afficher moins

**Comment by kiloutyg** [comment]
Seems inconsequential and not really seeing it anymore, beside the case of iframed pages
